#!/usr/bin/perl
use Net::SFTP::Foreign;
use File::Glob;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../../lib";
use PsN;

my $user = 	`whoami`;
chomp($user);

if ($user eq 'rikard'){
	$user = 'rikardno,psn';
}else{
	$user = 'k_harling,psn';
}

my $password = $ARGV[0];
unless (length($password) > 1){
	die "That is clearly not the right password";
}

#assume this is run from development/webpage
chdir('../../doc');

print "Trying sftp for user $user\n";

my $host='web.sourceforge.net';
my $path='htdocs/internal_release_pdfdocs';

my $sftp = Net::SFTP::Foreign->new($host,
								   user => $user,
								   password => $password
	);
$sftp->die_on_error("Unable to establish SFTP connection");


$sftp->setcwd($path) or die "unable to change cwd: " . $sftp->error;

my @pdfs = <*.pdf>;
#my @pdfs = ();

foreach my $file (@pdfs){
	print "Try put $file\n";
	$sftp->put($file,$file) or 	die "put failed: " . $sftp->error;
}

$path = '../internal_release_install_packages';
$sftp->setcwd($path) or die "unable to change cwd: " . $sftp->error;

my $zip = 'PsN-'.$PsN::version.'.zip';
my $tar = 'PsN-'.$PsN::version.'.tar.gz';

foreach my $file ($zip,$tar){
	my $localfile = '../'.$file;
	if (-e $localfile){
		print "Try put $localfile\n";
		$sftp->put($localfile,$file) or 	die "put failed: " . $sftp->error;
	}else{
		print "$localfile does not exist, skipping\n";
	}
}
