---
title: "Bootstrap"
output: pdf_document
classoption: landscape
geometry: margin=1.5cm
---

```{r loading_libraries_and_sourcing_functions,include = FALSE}
# get libPaths
source(file.path(rscripts.directory,"common/R_info.R"))
R_info(directory=working.directory,only_libPaths=T)
source(paste0(rscripts.directory, "/bootstrap/cook.cov.calcul.R"))
source(paste0(rscripts.directory, "/bootstrap/plot.cook.cov.R"))
source(paste0(rscripts.directory, "/bootstrap/format.dofv.data.R"))
source(paste0(rscripts.directory, "/bootstrap/plot.dofv.R"))
source(paste0(rscripts.directory, "/common/fix.column.names.R"))

library(xpose4)
library(ggplot2)
library(grid)
require(plyr)
require(dplyr)
#add R_info to the meta file
R_info(directory=working.directory)
```

```{r fix_column._ames,include = FALSE}
est.param.names <- fix_column_names(col_names=ESTIMATED.PARAMS)
```

```{r cook_scores_cov_ratios_plot,results='hide',echo=FALSE,fig.width=9,fig.height=6.5,fig.keep="high",fig.align="center"}
#calculate cook scores and cov ratios
list_cook.cov <- cook_cov_calcul(raw.results.file,included.ids.file,est.param.names)
#unlist
data_plots <- list_cook.cov$data_plots
failed_cov_ID <- list_cook.cov$failed_cov_ID
estimation_failures <- list_cook.cov$estimation_failures
samples <- list_cook.cov$samples

#plot cook scores and cov ratios to find influential individuals
if (rplots.level > 1) {
    gt <- plot_cook_cov(data_plots,failed_cov_ID,samples,estimation_failures)
    #plot
    grid.draw(gt)
}
```
\pagebreak

```{r check_xpose4_version,results='hide',echo=FALSE}
if(packageVersion("xpose4")<"4.5.0"){
		warning("xpose4 version must be 4.5.0 or later for bootstrap plot")	
}							 
```

```{r histograms_of_all_parameters,results='hide',warning=FALSE,echo=FALSE,fig.width=10,fig.height=7,fig.keep="high",fig.align="center"}
bootplots <- boot.hist(results.file=raw.results.file,incl.ids.file=included.ids.file,
                       min.failed=skip.minimization.terminated,
                       cov.failed=skip.covariance.step.terminated,
                       cov.warnings=skip.with.covstep.warnings,
                       boundary=skip.estimate.near.boundary)
print(bootplots[1]) #parameters
```
\pagebreak

```{r dOFV_distribution_plot,results='hide',warning=FALSE,message=FALSE,echo=FALSE,fig.width=10,fig.height=7,fig.keep="high",fig.align="center"}

add_dOFV_plots <- FALSE
if (dofv.is.run){
  add_dOFV_plots <- TRUE
  
  # Read in and format data
  list_dofv <- format_dofv_data(dofv.raw.results.file,raw.results.file,est.param.names)
  all <- list_dofv$all
  df_est <- list_dofv$df_est

  # Plot dOFV distributions
  qdOFV_all <- plot_dofv(all,df_est,est.param.names)
  print(qdOFV_all)
}
```

```{asis Add_pagebreak_on_condition, echo=add_dOFV_plots}
\pagebreak
```

```{r Histogram_of_objective_function,results='hide',echo=FALSE,fig.width=10,fig.height=7,fig.keep="high",fig.align="center"}

if (rplots.level > 1){
    print(bootplots[2:4]) #SEs ofv eigenvalues
}
```
