skipped.id.file <- paste0(working.directory, 'skipped_individuals1.csv')
source(paste0(rscripts.directory, "cdd/pdf.cdd.R"))
source(paste0(rscripts.directory,"cdd/create.data.full.R"))
source(paste0(rscripts.directory,"cdd/create.data.R"))
source(paste0(rscripts.directory,"cdd/cov.cook.par.data.R"))
source(paste0(rscripts.directory,"cdd/warnings.data.R"))
source(paste0(rscripts.directory,"cdd/mark.options.data.R"))
source(paste0(rscripts.directory,"cdd/failed.values.R"))
source(paste0(rscripts.directory,"cdd/plot.cdd.R"))
source(paste0(rscripts.directory,"cdd/cutoff.cov.cook.R"))
source(paste0(rscripts.directory,"cdd/delta.ofv.data.R"))
source(paste0(rscripts.directory,"cdd/plot.delta.ofv.R"))
source(paste0(rscripts.directory,"common/plot.table.R"))
pdf.cdd(raw.results.file,skipped.id.file,'PsN_cdd_plots.pdf',markeropt=1,
        cov.failed = TRUE, boundary = TRUE, legend = TRUE, cutoff_cook=0.8,cutoff_cov=2)