## PsN R script for plotting results of llp
## Justin Wilkins
## October 2005
## Lars Lindbom
## August 2006

## set basic options
## autogenerated code begins
## we can set other things, like colours, line types, layout, etc here if we wish

ofv       <- 3.843     # set this to the desired llp ofv tolerance
ci.lines  <- TRUE      # do we want grey broken lines for outer CI limits?
dofv.line <- TRUE      # do we want grey broken line for final model parameter estimate?
hline     <- TRUE      # do we want grey broken line for desired llp ofv tolerance?

## autogenerated code ends

## read file
llp.data <- read.csv("llplog1.csv")

## get number of parameters
n <- (length(colnames(llp.data)) - 1) / 2

pos <- 0
cols <- c()


## plots
for (i in 1:(n*2)) {
  if (pos != 1) {

    pos <- 1
    ## create data frame for each parameter
    p1 <- c(llp.data[i],llp.data[i+1])
    p1 <- as.data.frame(p1)
    p1 <- p1[!(apply(is.na(p1),1,any)),]
    
    parmlabel <- names(p1)[1]
    
    names(p1) <- c("Parameter", "dOFV")

    p1$Parameter <- as.numeric(as.vector(p1$Parameter))
    p1$dOFV <- as.numeric(as.vector(p1$dOFV))
    
    ## 3rd order polynomial
    fit  <- lm(p1$dOFV~p1$Parameter+I(p1$Parameter^2)+I(p1$Parameter^3))
    ## 4th order polynomial
    fit2 <- lm(p1$dOFV~p1$Parameter+I(p1$Parameter^2)+I(p1$Parameter^3)+I(p1$Parameter^4))
    
    if (max(p1$Parameter,na.rm=TRUE) > 0) {
      pmn <- min(p1$Parameter,na.rm=TRUE) - (max(p1$Parameter,na.rm=TRUE)/10)
      pmx <- max(p1$Parameter,na.rm=TRUE) + (max(p1$Parameter,na.rm=TRUE)/10)
    } else {
      pmn <- min(p1$Parameter,na.rm=TRUE) + (max(p1$Parameter,na.rm=TRUE)/10)
      pmx <- max(p1$Parameter,na.rm=TRUE) - (max(p1$Parameter,na.rm=TRUE)/10)      
    }
    
    pno <- 1000
    pdif <- pmx - pmn
    pit  <- pdif / pno
    pcur <- pmn
    bint1 <- FALSE
    bint2 <- FALSE
    
    pint1 <- NULL
    pint2 <- NULL
    
    ip <- 0 ## inflections - down is bad
    misfit <- 0
    
    pfn <- data.frame()
    mat.txt <- c()
   
    ## try third order first
    for (p in 1:pno) {
      pfit <- as.vector( fit$coefficients[1] + 
          (fit$coefficients[2] * pcur) +
          (fit$coefficients[3] * (pcur^2)) +
          (fit$coefficients[4] * (pcur^3)) 
        )
      addrow  <- c(pcur, pfit) 
      mat.txt <- c(mat.txt, addrow)
      
      if (p == 1) {
        pint1 <- pfit
        pint2 <- pfit
        pprev <- pfit
        tprev <- pcur 
      } else {
        ## going down
        if ((pfit <= ofv) && (pprev >= ofv)) {
          if (abs(pfit-ofv) <= abs(pprev-ofv)) {
            if (!bint1) {
              pint1 <- pcur
            }
          } else {
            pint1 <- tprev
            ## we have a number for int1
            bint1 <- TRUE
          }
        }
        ## going up
        if ((pfit >= ofv) && (pprev <= ofv)) {
          if (abs(pfit-ofv) <= abs(pprev-ofv)) {
            if (!bint2) {
              pint2 <- pcur
            }
          } else {
            pint2 <- tprev
            ## we have a number for int2
            bint2 <- TRUE
          }
        }
        ## have we reached the nadir of the parabola?
        if (pfit >= pprev) {
          ip <- 1
        }    
        if ((ip == 1) && (pfit < pprev)) {
          ## misfit 
          misfit <- 1
        }
        pprev <- pfit 
        tprev <- pcur 
      }
      pcur <- pcur + pit
    }
    
    if (misfit) {
      ## try fourth order fit
      pno <- 1000
      pdif <- pmx - pmn
      pit  <- pdif / pno
      pcur <- pmn
      bint1 <- FALSE
      bint2 <- FALSE
    
      pint1 <- NULL
      pint2 <- NULL
    
      pfn <- data.frame()
      mat.txt <- c()
    
      for (p in 1:pno) {
        pfit <- as.vector( fit2$coefficients[1] + 
            (fit2$coefficients[2] * pcur) +
            (fit2$coefficients[3] * (pcur^2)) +
            (fit2$coefficients[4] * (pcur^3)) +
            (fit2$coefficients[5] * (pcur^4)) 
          )
        addrow  <- c(pcur, pfit) 
        mat.txt <- c(mat.txt, addrow)
      
        if (p == 1) {
          pint1 <- pfit
          pint2 <- pfit
          pprev <- pfit
          tprev <- pcur 
        } else {
          ## going down
          if ((pfit <= ofv) && (pprev >= ofv)) {
            if (abs(pfit-ofv) <= abs(pprev-ofv)) {
              if (!bint1) {
                pint1 <- pcur
              }
            } else {
              pint1 <- tprev
              ## we have a number for int1
              bint1 <- TRUE
            }
          }
          ## going up
          if ((pfit >= ofv) && (pprev <= ofv)) {
            if (abs(pfit-ofv) <= abs(pprev-ofv)) {
              if (!bint2) {
                pint2 <- pcur
              }
            } else {
              pint2 <- tprev
              ## we have a number for int2
              bint2 <- TRUE
            }
          }
          ## have we reached the nadir of the parabola?
          if (pfit >= pprev) {
            ip <- 1
          }    
          if ((ip == 1) && (pfit < pprev)) {
            ## misfit 
            misfit <- 1
          }
          pprev <- pfit 
          tprev <- pcur 
        }
        pcur <- pcur + pit
      }      
    }
    
    mdat <- matrix(mat.txt, nrow = pno, ncol=2, byrow=TRUE,
      dimnames = list(c(), c("Parameter", "dOFV")))
    
    llp.parabola <- as.data.frame(mdat)
    
#    postscript(file=paste("llp.", parmlabel, ".ps", sep=""), paper="a4",
#      title=paste("Log-likelihood profile - ", parmlabel, sep=""),
#      horizontal=T)   
    pdf(file=paste("llp.", parmlabel, ".pdf", sep=""), paper="special",
        title=paste("Log-likelihood profile - ", parmlabel, sep=""),width=10,height=7)   
      
    plot (llp.parabola$Parameter, llp.parabola$dOFV,
      type="l",
      # ylim=c(0,max(data.main$DV,na.rm=TRUE)),
      ylab="dOFV",
      xlab=parmlabel,
      main=paste("Log-likelihood profile - ", parmlabel, sep="")
      #sub="Binning tolerance: 0.25, occasion: 0"
      ) 
      
    points(p1$Parameter, p1$dOFV, col="red", pch=21)
    abline(v=pint1, col="red", lty=2)
    abline(v=pint2, col="red", lty=2)
    text(pint1, ofv, labels=signif(pint1, digits = 3), cex = .8, adj = c(0,0), pos='4')
    text(pint2, ofv, labels=signif(pint2, digits = 3), cex = .8, adj = c(0,0), pos='4')
    text(p1[1,1], 0, labels=signif(p1[1,1], digits = 3), cex = .8, adj = c(0,0), pos='3')
    
    if (ci.lines) {
      abline(v=min(p1$Parameter,na.rm=TRUE), col="gray", lty=2)
      abline(v=max(p1$Parameter,na.rm=TRUE), col="gray", lty=2)
    }
    
    if (dofv.line) {
      abline(v=p1[1,1], col="gray", lty=2)
    }
    
    if (hline) {
      abline(h=ofv, col="gray", lty=2)
    }
    
  } else {
    pos <- 0
  }
}


