---
title: "Quality assurance"
output: pdf_document # delete if html file needed and set type <- 'html'
header-includes: #needed to create a pdf file
    - \usepackage{colortbl}
    - \usepackage{longtable}
geometry: margin=1.5cm
classoption: a4paper
---

```{r loading_libraries_and_sourcing_functions,include=F,warning=F,message=F}
library(PsNR)
library(magrittr)
# library(tidyverse)
# library(knitr)
# library(methods)
# library(expm)
# library(vpc)
# library(xpose)
# library(PEIP)
# library(yaml)
# library(devtools)
# library(mvtnorm)
# library(kableExtra)
options(knitr.table.format=type)
# check needed package versions
# source(file.path(rscripts.directory, "/common/check_package_versions.R"))
# check_package_versions(pkg=c("tidyverse","xpose","kableExtra","expm","PEIP","yaml","devtools"),
#                        versions=c("1.1.1","0.4.0","0.6.1","0.999-1","2.0-1","2.1.14","1.13.3"),
#                        toolname)
# #load functions
# source(file.path(rscripts.directory, "common/R_info.R"))
# source(file.path(rscripts.directory, "common/find_r_files_in_subdir.R"))
# source(file.path(rscripts.directory, "common/iofv.R"))
# source(file.path(rscripts.directory, "common/keep_symbols.R"))
# source(file.path(rscripts.directory, "common/command_start.finish.time.R"))
# source(file.path(rscripts.directory, "common/additional_info.R"))
# source(file.path(rscripts.directory, "common/break_text.R"))
# source(file.path(rscripts.directory, "common/get_initial_estimates_from_ext.R"))
# source(file.path(rscripts.directory, "common/kable_table.R"))
# source(file.path(rscripts.directory, "cdd/create.data.full.R"))
# source(file.path(rscripts.directory,"frem/ID_ratio_function.R"))
# source(file.path(rscripts.directory,"frem/parameter_ratio_function.R"))
# source(file.path(rscripts.directory,"frem/sd_of_unexpl_var_function.R"))
# #source qa functions
# rscript <- find_r_files_in_subdir(toolname,rscripts.directory)
# for (i in 1:length(rscript)) {
#   source(rscript[i])
# }
# rscript <- find_r_files_in_subdir("simeval",rscripts.directory)
# for (i in 1:length(rscript)) {
#   source(rscript[i])
# }
```

```{r add_info_to_meta_yaml_file, include=F}
#add R_info to the meta file
R_info(directory=working.directory)
```

<!-- ##############################   Calculations  #################################### -->

```{r find_resmod_folders,include=F,warning=F,message=F}
#which "resmod_ ..." folders are in the working directory
idv_all <- which_resmod_folders(directory=working.directory,idv_name)
```

```{r summary_about_ofv_values,results='asis',echo=F,warning=F,message=F,eval=!nonlinear}
ofv_table <- ofv_summary_table(working.directory,model.filename)
```

```{r structural_model_calculations,results='hide',echo=F,warning=F,message=F}
# 1.Structural models
structural_overview <- get_structural_overview_table(directory=working.directory,idv=idv_all,dvid_name,skip)
if(all(skip!="resmod")) {
  # get resmod structural details tables
  resmod_structural_details <- resmod_structural_details_tables(working.directory,base_dataset,original_max0_model=original_max0_model,extra_table,extra_table_columns,idv_all,dvid_name,nonlinear)
}
```

```{r parameter_model_calculations,results='hide',echo=F,warning=F,message=F}
# 2.Parameter Variability Models
list_par_var_models <- get_param_var_tables(directory=working.directory,base_model,skip)
if(list_par_var_models$fullblock_mod) {
  full_omega_block_list <- get_full_omega_block(original_max0_model=original_max0_model,
                                                fullblock_model=file.path(working.directory,"modelfit_run/fullblock.mod"),
                                                dofv_block=list_par_var_models$dofv_block)
}
if(list_par_var_models$boxcox_mod) {
  boxcox_lambdas_list <- get_param_extra_table(original_max0_model=original_max0_model,
                                               param_model=file.path(working.directory,"modelfit_run/boxcox.mod"),
                                               dofv=list_par_var_models$dofv_box)
  boxcox_lambdas_orig <- boxcox_lambdas_list$param_extra_table_orig
}
if(list_par_var_models$tdist_mod) {
  tdist_list <- get_param_extra_table(original_max0_model=original_max0_model,
                                      param_model=file.path(working.directory,"modelfit_run/tdist.mod"),
                                      dofv=list_par_var_models$dofv_tdist)
  tdist_table_orig <- tdist_list$param_extra_table_orig
}
if(list_par_var_models$add_etas_mod) {
  add_etas_list <- get_add_etas_table(original_max0_model=original_max0_model,
                                      add_etas_dir=file.path(working.directory,"add_etas_run"),
                                      added_etas=added_etas,
                                      dofv_add.etas=list_par_var_models$dofv_add_etas,
                                      nonlinear)
}
if(list_par_var_models$iov_mod) {
  iov_list <- get_iov_table(original_max0_model=original_max0_model,
                            iov_model=file.path(working.directory,"modelfit_run/iov.mod"),
                            iov_etas=iov_etas,
                            dofv_iov=list_par_var_models$dofv_iov)
}
```

```{r boxcox_shape_table_for_plot,results='hide',echo=F,warning=F,message=F}
if(exists("boxcox_lambdas_orig") && !boxcox_lambdas_list$param_extra_table_error) {
  eta_table_boxcox <- get_eta.etat_values(param_model=file.path(working.directory,"modelfit_run/boxcox.mod"),theta_values=boxcox_lambdas_orig[,1:2])
  list_boxcox_shape <- get_eta_transf_table(input_table=boxcox_lambdas_orig)
  make_boxcox_shape_plot <- list_boxcox_shape$make_eta_transf_plot
  fig_height_boxcox <- list_boxcox_shape$fig_height
} else {
  fig_height_boxcox <- 15
  make_boxcox_shape_plot <- FALSE
}
```

```{r tdist_shape_table_for_plot,results='hide',echo=F,warning=F,message=F}
if(exists("tdist_table_orig") && !tdist_list$param_extra_table_error) {
  eta_table_tdist <- get_eta.etat_values(param_model=file.path(working.directory,"modelfit_run/tdist.mod"),theta_values=tdist_table_orig[,1:2])
  list_tdist_shape <- get_eta_transf_table(input_table=tdist_table_orig)
  make_tdist_shape_plot <- list_tdist_shape$make_eta_transf_plot
  fig_height_tdist <- list_tdist_shape$fig_height
} else {
  fig_height_tdist <- 15
  make_tdist_shape_plot <- FALSE
}
```

```{r covariate_model_calculations,results='hide',echo=F,warning=F,message=F}
# 3.Covariate Models
  # 3.1.All (FREM)
frem_table_list <- get_all_covariates(frem_directory=file.path(working.directory,"frem_run"),continuous,categorical,parameters,list_par_var_models$dofv_block,skip)
 # 3.2.Covariate (SCM)
scm_table_list <- get_scm_table(scm_directory=file.path(working.directory,"scm_run"),
                                parameters,continuous,scm_categorical,skip)
# summary
covariates_table_list <- get_covariates_table(frem_table_list$frem_table,scm_table_list$scm_table,scm_table_list$max_scm_table)
```

```{r residual_error_model_calculations,results='hide',echo=F,warning=F,message=F}
#4.create residual error model table (extra table)
resmod_table_list <- get_resmod_ruv_table(directory=working.directory,idv_name,dvid_name,skip)
```

```{r influential_individuals_calculations,results='hide',echo=F,warning=F,message=F}
# 5.Influential individuals (CDD)
ii_list <- get_ii_table(cdd_directory=file.path(working.directory,"cdd_run"),
                        model.filename=model.filename,
                        cutoff=cdd_dofv_cutoff,
                        max_rows=cdd_max_rows,
                        skip,
                        nonlinear)
```

```{r outliers_calculations,results='hide',echo=F,warning=F,message=F}
# 6.Outliers (Simeval)
outlier_table_list <- get_outliers_table(simeval_directory=file.path(working.directory, "simeval_run"),ii_list$cdd.data,skip)
```

```{r make_overview_table,results='hide',echo=F,warning=F,message=F}
# get overview table
overview_table_list <- get_overview_table(structural_overview=structural_overview,
                                          param_var_overview=list_par_var_models$par_var_models,
                                          covariates_overview=covariates_table_list$covariates_table,
                                          resmod_ruv_overview=resmod_table_list$resmod_ruv_overview,
                                          infl_indiv_overview=ii_list$cdd_highest_dofv,
                                          outliers_overview=outlier_table_list$max_outlier_table)
```

<!-- #######################   Write Rmarkdown document here   ################################ -->
```{r command_text_from_command_line,results='asis',echo=F,warning=F,message=F}
command_runtime <- command_start.finish.time(yaml_file=file.path(working.directory,"meta.yaml"))
if(length(command_runtime$command)>0 && length(command_runtime$run_start)>0 && length(command_runtime$run_finish)>0) {
  cat(break_text(command_runtime$command,max_symb=95),"\n\n")
  cat(command_runtime$run_start,"\n\n")
  cat(command_runtime$run_finish,"\n\n")
}
```

```{r draw_ofv_table,results='asis',echo=F,warning=F,message=F,eval=!nonlinear}
ofv_table_print <- kable_table(ofv_table,format=type,booktabs=T,longtable=T,align=c("l","l"),linesep="") %>%
  kableExtra::kable_styling(position="c",full_width = F)
print(ofv_table_print)
```

```{r draw_overview_table,results='asis',echo=F,warning=F,message=F}
cat("#Overview\n\n")
overview_table <- kable_table(overview_table_list$overview_table,format=type,booktabs=T,longtable=T,align=c("l","r","c"),linesep="") %>%
  kableExtra::kable_styling(position="c",full_width = F)
for(i in 1:nrow(overview_table_list$row_groups)) {
  overview_table <- overview_table %>% kableExtra::group_rows(overview_table_list$row_groups[i,1],overview_table_list$row_groups[i,2],overview_table_list$row_groups[i,3])
}
print(overview_table)
cat("Overview of possible modifications to different model aspects, expected improvement in OFV as well as number of additional parameters used.")
```

```{r draw_structural_details_tables,eval=all(skip!="resmod"),results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=6.5,fig.keep="high",fig.align="center"}
cat("\\pagebreak\n\n")
cat("#Structural\n\n")
all_structural_extra_plots(simeval_directory=file.path(working.directory,"simeval_run"),base_dataset,resmod_structural_details,
                           extra_table,idv_all,idv_name,dvid_name,type,nonlinear)
```

```{r Add_text_for_parameter_section_if_exist_mod_files,eval=all(skip!="transform"),results='asis',echo=F,warning=F,message=F}
cat("\\pagebreak\n\n")
cat("#Parameter Variability Model\n\n")
```

```{r draw_full_omega_block_table,eval=all(skip!="transform"),results='asis',echo=F,warning=F,message=F}
cat("##Full OMEGA Block\n\n")
if(list_par_var_models$fullblock_mod) {
  full_omega_block_table <- kable_table(full_omega_block_list$full_omega_block_table,format=type,booktabs=T,longtable=T,align = c("l","r","r"),linesep="") %>%
    kableExtra::kable_styling(position="c",full_width = F) %>%
    kableExtra::row_spec(nrow(full_omega_block_list$full_omega_block_table),bold=T)
  print(full_omega_block_table)
  cat("Estimated standard deviation (sd) and correlation (corr) as well as expected improvement in OFV when allowing for a full block correlation structure between subject-level random effects.")
} else {
  cat("Model already has full OMEGA Block.")
}
```

```{r draw_boxcox_tranformation_table,eval=all(skip!="transform"),results='asis',echo=F,warning=F,message=F}
cat("##Box-Cox Transformation\n\n")
boxcox_lambdas_table <- kable_table(boxcox_lambdas_list$param_extra_table,format=type,booktabs=T,longtable=T,align = c("l","r","r","r"),linesep="") %>%
  kableExtra::kable_styling(position="c",full_width = F) %>%
  kableExtra::row_spec(nrow(boxcox_lambdas_list$param_extra_table),bold=T)
print(boxcox_lambdas_table)
cat("Estimated shape parameters (Lambda) as well as expected improvement in OFV when estimating a Box-Cox transformation for each subject-level random effect.")
```

```{r plot_boxcox_shape,eval=(make_boxcox_shape_plot && all(skip!="transform")), results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=fig_height_boxcox,fig.keep="high",fig.align="center"}
boxcox_shape_plot <- plot_transformed_density(data_table=list_boxcox_shape$eta_transf_table,eta_table_boxcox,param_model="boxcox")
for(i in 1:length(boxcox_shape_plot)) {
  print(boxcox_shape_plot[[i]])
  cat("Density of the Box-Cox transformed random effect in comparison with the density of the original (untransformed) random effect. The rug below the densities indicates the empirical Bayes estimates for the transformed random effect.")
}
```

```{r draw_add_etas_table,eval=all(skip!="transform"),results='asis',echo=F,warning=F,message=F}
if(!boxcox_lambdas_list$param_extra_table_error) {
  cat("\\pagebreak\n\n")
}
cat("##Additional etas\n\n")
if(list_par_var_models$add_etas_mod) {
  add_etas_table <- kable_table(add_etas_list$add_etas_table,format=type,booktabs=T,longtable=T,align = c("l","r","r","r"),linesep="") %>%
    kableExtra::kable_styling(position="c",full_width = F) %>%
    kableExtra::row_spec(nrow(add_etas_list$add_etas_table),bold=T)
  print(add_etas_table)
  cat("Consequences of including additional subject-level random effects on selected parameters in terms of estimated standard deviation (SD) of new and existing random effect parameters as well as expected improvement in OFV.")
} else {
  cat("No additional etas were added.")
}
```

```{r draw_tdist_table,eval=all(skip!="transform"),results='asis',echo=F,warning=F,message=F}
cat("##t-distribution\n\n")
tdist_table <- kable_table(tdist_list$param_extra_table,format=type,booktabs=T,longtable=T,align = c("l","r","r","r"),linesep="") %>%
  kableExtra::kable_styling(position="c",full_width = F) %>%
  kableExtra::row_spec(nrow(tdist_list$param_extra_table),bold=T)
print(tdist_table)
cat("Estimated degrees of freedom as well as expected improvement in OFV when estimating a t-distribution transformation for each subject-level random effect.")
```

```{r plot_tdist_shape,eval=(make_tdist_shape_plot && all(skip!="transform")), results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=fig_height_tdist,fig.keep="high",fig.align="center"}
tdist_shape_plot <- plot_transformed_density(data_table=list_tdist_shape$eta_transf_table,eta_table=eta_table_tdist,param_model="tdist")
for(i in 1:length(tdist_shape_plot)) {
  print(tdist_shape_plot[[i]])
  cat("Density of the t-distribution transformed random effect in comparison with the density of the original (untransformed) random effect. The rug below the densities indicates the empirical Bayes estimates for the transformed random effect.")
}
```

```{r draw_iov_table,eval=all(skip!="transform"),results='asis',echo=F,warning=F,message=F}
if(make_tdist_shape_plot && (list_par_var_models$add_etas_mod || list_par_var_models$iov_mod)) {
  cat("\\pagebreak\n\n")
}
cat("##Interoccasion variability\n\n")
if(list_par_var_models$iov_mod) {
  iov_table <- kable_table(iov_list$iov_table,format=type,booktabs=T,longtable=T,align = c("l","r","r","r"),linesep="") %>%
    kableExtra::kable_styling(position="c",full_width = F) %>%
    kableExtra::row_spec(nrow(iov_list$iov_table),bold=T)
  if(!iov_list$iov_error) {
    iov_table <- iov_table %>% kableExtra::add_header_above(c(" "=1,"New SD"=2," "=1))
  }
  print(iov_table)
  cat("Consequences of including inter-occasion variability in terms of estimated standard deviation (SD) for inter-individual (IIV) and inter-occasion variability (IOV) as well as expected improvement in OFV.")
} else {
  cat("No interoccasion variability was added.")
}
```

```{r draw_covariates_table,eval=(all(skip!="frem")||all(skip!="scm")),results='asis',echo=F,warning=F,message=F}
cat("\\pagebreak\n\n")
cat("#Covariates\n\n")
align <- paste(c("l",rep("r",ncol(covariates_table_list$covariates_extra_table)-1)),collapse = '')
covariates_extra_table <- kable_table(covariates_table_list$covariates_extra_table,format=type,booktabs=T,longtable=T,linesep="",align = align) %>%
  kableExtra::kable_styling(position="c",full_width = F) %>%
  kableExtra::row_spec((nrow(covariates_table_list$covariates_extra_table)-1):nrow(covariates_table_list$covariates_extra_table),bold=T)
print(covariates_extra_table)
cat("Model parameter covariate relationship, resulting improvement in OFV and estimated covariate coefficient. Furthermore, the sum of all univariate improvements in OFV ignoring between covariate correlations (sum(SCMu)), as well as joint improvement in OFV when taking correlations into account (FREM).")
```

```{r draw_frem_plots,eval=(all(skip!="frem")||all(skip!="scm")),results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=14.5,fig.keep="high",fig.align="center"}
all_frem_plots(file.path(working.directory, 'frem_run', 'postfrem_run'))
```

```{r draw_resiual_error_model_table,eval=all(skip!="resmod"),results='asis',echo=F,warning=F,message=F,fig.width=8,fig.height=6,fig.keep="high",fig.align="center"}
cat("\\pagebreak\n\n")
cat("#Residual Error Model\n\n")
if(!nonlinear && file.exists(sub("(\\.[^.]+)$",".lst",original_max0_model)) &&
   file.exists(file.path(working.directory,paste0("resmod_",idv_name),"results.csv"))) {
  xpdb_data <- xpose::xpose_data(file = sub("(\\.[^.]+)$",".lst",original_max0_model)) %>%
    qa_data(resmod_folder=file.path(working.directory,paste0("resmod_",idv_name)),derivatives_model=original_max0_model)
}
for (i in 1:length(resmod_table_list$dvid_nr)) {
  if(!nonlinear && exists("xpdb_data")) {
    xpdb <- xpdb_data %>% add_resmod_xpdbs(resmod_folder=file.path(working.directory,paste0("resmod_",idv_name)),  dvid_value=resmod_table_list$dvid_nr[i])
  }
  if(resmod_table_list$dvid_nr[i] != 'NA') {
    cat(paste0("##",dvid_name,"=",resmod_table_list$dvid_nr[i],"\n\n"))
  }
  resmod_ruv_models_table <- kable_table(resmod_table_list$resmod_ruv_table_list[[i]],format=type,booktabs=T,longtable=T,align = c("l","r","c","l"),linesep="") %>%
    kableExtra::kable_styling(position="c",full_width = F)
  print(resmod_ruv_models_table)
  cat("Residual error model, resulting expected improvement in OFV, required additional model parameters as well as their estimates.\n\n\n\n")
  if(!nonlinear && exists("xpdb")) {
    res_var_attribution <- resmod_variability_attribution(xpdb,dvid_col_name=dvid_name,dvid_value=resmod_table_list$dvid_nr[i],smooth=TRUE)
    print(res_var_attribution)
    cat("\n\n Attribution of variability to between-subject random effects and residual unexplained variability (RUV) versus independent variable under different residual error models.")
    cat("\\pagebreak\n\n")
  #   res_shrinkage <- resmod_shrinkage(xpdb,dvid_col_name=dvid_name,dvid_value=resmod_table_list$dvid_nr[i])
  #   align <- paste(c("l",rep("r",ncol(res_shrinkage)-1)),collapse = '')
  #   res_shrinkage <- kable_table(res_shrinkage,format=type,booktabs=T,longtable=T,linesep="",align = align) %>%
  #     kableExtra::kable_styling(position="c",full_width = F)
  #   print(res_shrinkage)
  #   cat("Expected shrinkage for between-subject random effects under different residual error models.\n\n")
  # cat("\\pagebreak\n\n")
  }
}
```

```{r draw_influential_individuals_table,eval=all(skip!="cdd"),results='asis',echo=F,warning=F,message=F}
cat("\\pagebreak\n\n")
cat("#Influential Individuals\n\n")
if(ncol(ii_list$ii_table)==1 && nrow(ii_list$ii_table)==1) {
  cat(paste0(as.character(ii_list$ii_table[1,1]),"."),"\n\n")
} else {
  ii_table <- kable_table(ii_list$ii_table,booktabs=T,longtable=T,align = c("l","r"),linesep="",format=type) %>%
  kableExtra::kable_styling(position="c",full_width = F)
print(ii_table)
}
cat("Subjects identified as significantly influencing the model fit for all other subjects and their influence in terms of improvement in OFV for other subjects when excluding them during the fit.")
```

```{r histogram_of_cdd_dofv,eval=all(skip!="cdd"),results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=6}
cdd_hist <- hist_of_cdd_dofv(values=ii_list$all_dofv)
if(length(ii_list$all_dofv)>0) {
  print(cdd_hist)
  cat("Distribution of OFV improvements (dOFV) when excluding specific subjects during the fit.")
}
```

```{r add_infl_indiv_individual_plots,eval=all(skip!="cdd"),results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=ii_list$fig_height_infl}
if(length(ii_list$infl_id)>0) {
  infl.ind_individual_plots <- individual_plots_extra(file_name=original_max0_model,ID_nr=ii_list$infl_id[1:10],dvid_name=dvid_name)
  print(infl.ind_individual_plots)
  cat("Observations (DV), individual predictions (IPRED) and population predictions (PRED) versus time for subjects identified as influential.")
}
```

```{r draw_outliers_table,eval=all(skip!="simeval"),results='asis',echo=F,warning=F,message=F}
cat("\\pagebreak\n\n")
cat("#Outliers\n\n")
if(ncol(outlier_table_list$outliers_table)==1 && nrow(outlier_table_list$outliers_table)==1) {
  cat(paste0(as.character(outlier_table_list$outliers_table[1,1]),"."),"\n\n")
} else {
  outliers_table <- kable_table(outlier_table_list$outliers_table,format=type,booktabs=T,longtable=T,align = c("l","r"),linesep="") %>%
  kableExtra::kable_styling(position="c",full_width = F)
print(outliers_table)
}
cat("Subjects identified as outliers based on a worse than expected model fit and the corresponding improvement in OFV when excluding them during the fit.")
```

```{r plot_outliers,eval=all(skip!="simeval"),results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=6}
if(file.exists(file.path(working.directory,"simeval_run/raw_all_iofv.csv"))) {
  list_i_ofv_res <- i_ofv_res(file.path(working.directory,"simeval_run/raw_all_iofv.csv"),show.warning=F)# calculation
  n.subjects <- list_i_ofv_res$n.subjects
  # Make a boxplot
  boxplot_i_ofv_res(list_i_ofv_res,n.subjects,add_title=FALSE)
  cat("Range of deviation of individual OFVs between observed and simulated data for all subjects in standard deviations from the expected fit (iOFV RES).  High iOFV RES values indicate subjects for which the model describe the data worse than expected.")
}
```

```{r add_outliers_individual_plots,eval=all(skip!="simeval"),results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=outlier_table_list$fig_height_outl}
if(length(outlier_table_list$outlier_ids)>0) {
  outlier_individual_plots <- individual_plots_extra(file_name=original_max0_model,ID_nr=outlier_table_list$outlier_ids,dvid_name=dvid_name)
  print(outlier_individual_plots)
  cat("Observations (DV), individual predictions (IPRED) and population predictions (PRED) versus time for subjects identified as outliers.")
}
```

```{r add_all_outliers_overall_table,eval=all(skip!="simeval"),results='asis',echo=F,warning=F,message=F}
all_outl_list <- simeval_all_ouliers_table(simeval_directory=file.path(working.directory,"simeval_run"))
if(all_outl_list$files_exist) {
  simeval_overall_outliers_table <- kable_table(all_outl_list$all_outlier_table,booktabs=T,format=type,longtable=T,align = c("l","c","c","c","c","c"),linesep="") %>%
    kableExtra::kable_styling(position="c",full_width = F)
if(!(is.null(all_outl_list$add_header_above))) {
  simeval_overall_outliers_table <- simeval_overall_outliers_table %>% kableExtra::add_header_above(all_outl_list$add_header_above,bold=T)
}
  cat("\\pagebreak\n\n")
  print(simeval_overall_outliers_table)
  cat("Subjects marked as outliers and the metrics used to identify them: (1) OFV outliers have a worse than expected fit, (2) EBE NPDE outliers show significant deviation in their empirical Bayes estimates and (3) CWRES outliers have observations with worse than expected residuals.")
}
```

```{r plot_iofv_vs_iofv,eval=(rplots.level > 1),results='asis',echo=F,warning=F,message=F,fig.width=11,fig.height=6,fig.keep="high",fig.align="center"}
phi1 <- file.path(working.directory,"linearize_run/scm_dir1",paste0(sub('.([^.]*)$','',model.filename),"_linbase.phi"))
phi2 <- file.path(working.directory,"linearize_run/scm_dir1/derivatives.phi")
make_iofv_plot <- iofv_vs_iofv(phi1,phi2)$make_plot
if(make_iofv_plot) {
  cat("\\pagebreak\n\n")
  cat("#Sanity checks\n\n")
  plot_iofv_vs_iofv <- iofv_vs_iofv(phi1,phi2)$plot
  print(plot_iofv_vs_iofv)
  cat("Agreement in individual OFV contribution (iOFV) between non-linear and linearized model. Deviations from the line of identity indicate problems in the model linearization step and warrant caution when interpreting the results of this report.")
}
```

```{r additional_info,results='asis',echo=F,warning=F,message=F}
if(file.exists(file.path(working.directory,"meta.yaml"))) {
  cat("\\pagebreak\n\n")
  cat("#Additional information\n\n")
  add_info <- additional_info(yaml_file=file.path(working.directory,"meta.yaml"))
  cat("PsN_version:",add_info$PsN_version,"\n\n")
  cat("NONMEM_version:",add_info$NONMEM_version,"\n\n")
  cat("R_version:",add_info$R_version,"\n\n")
  cat("Loaded_R_packages:\n\n")
  R_packages <- kable_table(add_info$R_packages,format=type,booktabs=T,longtable=T,align=c("l","l","l"),linesep="") %>%
    kableExtra::kable_styling(position="c",full_width = F)
  print(R_packages)
}
```

```{r yaml_summary,results='asis',echo=F,warning=F,message=F}
yaml_summary(model.filename,
             ofv_table,
             resmod_structural_details,
             full_omega_block_list,
             boxcox_lambdas_list,
             tdist_list,add_etas_list,
             iov_list,
             frem_table_list,
             scm_table_list,
             resmod_table_list,
             ii_list,
             outlier_table_list,
             overview_table_list,
             dvid_name,
             skip,
             idv_all)
```
