install.packages("caTools", dependencies=TRUE)
install.packages("expm", dependencies=TRUE)
install.packages("gplots", dependencies=TRUE)
install.packages("grid", dependencies=TRUE)
install.packages("gridExtra", dependencies=TRUE)
install.packages("MASS", dependencies=TRUE)
install.packages("MCMCpack", dependencies=TRUE)
install.packages("rmarkdown",dependencies = TRUE)
install.packages("ggthemes", dependencies=TRUE)
install.packages("PEIP", dependencies=TRUE)
install.packages("PerformanceAnalytics", dependencies=TRUE)
install.packages("plotrix", dependencies=TRUE)
install.packages("plyr", dependencies=TRUE)
install.packages("RColorBrewer", dependencies=TRUE)
install.packages("reshape", dependencies=TRUE)
install.packages("reshape2", dependencies=TRUE)
install.packages("scales", dependencies=TRUE)
install.packages("stats4", dependencies=TRUE)
install.packages("tidyverse", dependencies=TRUE)
install.packages("xpose4", dependencies=TRUE)
install.packages("ztable", dependencies=TRUE)
install.packages("devtools", dependencies=TRUE)
install.packages("yaml", dependencies=TRUE)
devtools::install_github("UUPharmacometrics/xpose")
devtools::install_github("ronkeizer/vpc")
