---
title: "VPC"
output: pdf_document
classoption: landscape
geometry: margin=1.5cm
---

```{r loading_libraries, warning=FALSE, message=FALSE, include = FALSE}
# get libPaths
library(PsNR)
library(magrittr)
library(methods)
library(xpose4)
library(vpc)
library(ggplot2)

#add R_info to the meta file
R_info(directory=working.directory)
meta <- PsNR::metadata(working.directory)
```

```{r vpc_plots, warning=FALSE, message=FALSE, results='asis',echo=FALSE,fig.width=9,fig.height=6.5,fig.keep="high",fig.align="center"}

if (is.tte) {
    #data is in the model directory, go there to read input
    setwd(dirname(PsNR::model_path(meta)))
    xpdb <- xpose4::xpose.data(xpose.runno)
    plots <- xpose4::kaplan.plot(object=xpdb, VPC=T)
    #go back to vpc directory 
    setwd(working.directory)
} else if (is.categorical) { 
    plots <- xpose4::xpose.VPC.categorical(vpc.info=tool.results.file, vpctab=vpctab)
} else if (have.loq.data | have.censored) {
    plots <- xpose4::xpose.VPC.both(vpc.info=tool.results.file, vpctab=vpctab)
} else {
    plots <- xpose4::xpose.VPC(vpc.info=tool.results.file, vpctab=vpctab)
}
print(plots) 
```

```{r mix_plots, warning=FALSE, message=FALSE, results='asis',echo=FALSE,fig.width=17,fig.height=12,fig.keep="high",fig.align="center"}
if (exists('mix')) {     # A mixture model is a special case
    if (require("vpc")) {
        observations_tablefile <- paste0(working.directory, '/m1/vpc_original.npctab.dta')
        simulations_tablefile <- paste0(working.directory, '/m1/vpc_simulation.1.npctab.dta')

        obs <- read_nonmem_table(observations_tablefile)
        sim <- read_nonmem_table(simulations_tablefile)
        obs_phm <- read_nonmem_table(phm_obs_file)
        sim_phm <- read_nonmem_table(phm_sim_file)
        if (!exists('stratify_on')) {
            stratify_on <- NULL
        }

        # Read name of IDV from vpc_results.csv
        vpc_res <- read.csv(paste0(working.directory, '/vpc_results.csv'), skip=1, nrows=1, stringsAsFactors=FALSE)
        idv <- trimws(vpc_res$Independent.variable)

        vpc <- vpc::vpc(obs=obs, sim=sim, obs_cols=list(dv=dv, idv=idv), sim_cols=list(dv=dv, idv=idv), stratify=stratify_on, bins=bin_boundaries)
        print(vpc)
        plots_mixest <- mixture_vpc(obs, sim, obs_phm, sim_phm, dv=dv, idv=idv, bins=bin_boundaries, stratify_on=stratify_on)
        plots_randomized <- mixture_vpc(obs, sim, obs_phm, sim_phm, dv=dv, idv=idv, bins=bin_boundaries, stratify_on=stratify_on, randomize=TRUE)
        plots <- list()
        for (i in 1:length(plots_mixest)) {
            mixest <- plots_mixest[[i]]
            randomized <- plots_randomized[[i]]
            if (is.character(mixest) || is.character(randomized)) {     # An error message instead of plot
                cat("\\pagebreak\n\n")
                cat(p)
                cat("\\pagebreak")
            } else {
                plots[[2*i - 1]] <- mixest
                plots[[2*i]] <- randomized
            }
        }
        print(gridExtra::marrangeGrob(plots, nrow=2, ncol=2, top=NULL, padding=0))

        plots <- list()
        for (i in unique(obs_phm$SUBPOP)) { # Allowing cases with more than 2 mixtures
            temp_obs <- obs_phm %>% dplyr::filter(SUBPOP == i) %>% 
                        dplyr::arrange(PMIX) %>% 
                        dplyr::mutate(rank=1:dplyr::n()) # Get rank for the plot
            temp_sim <- sim_phm %>% dplyr::filter(SUBPOP == i) %>% 
                    dplyr::group_by(replicate) %>% # Assuming replicate is the simulation number
                    dplyr::arrange(PMIX) %>% 
                    dplyr::mutate(rank = 1:dplyr::n()) %>%  # Get rank for the plot by simulation
                    dplyr::group_by(rank) %>% 
                    dplyr::summarise(per5=quantile(PMIX, probs=c(0.05)), 
                                     per95=quantile(PMIX, probs=c(0.95))) # Get percentiles among simulations

            plots[[i]] <- ggplot() + 
                          geom_ribbon(data=temp_sim, aes(rank, ymin=per5, ymax=per95), alpha=0.2) +
                          geom_text(data=temp_obs, aes(rank, PMIX, label=SUBJECT_NO), size=8) +
                          geom_hline(yintercept=0.5, linetype="dashed", size=2) +
                          theme_classic() +
                          theme(axis.text.y=element_text(size=20),
                                axis.title.y=element_blank(),
                                axis.ticks.y=element_line(size=3),
                                axis.ticks.length=unit(6, "pt"),
                                axis.ticks.x=element_blank(),
                                axis.title.x=element_text(size=25),
                                axis.text.x=element_blank()) +
                          xlab(paste0("SUBPOP=", i))
            if (i > 1) {
                plots[[i]] <- plots[[i]] + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank())
            }
        }
        
        left_axis = grid::textGrob("IPmix", gp=grid::gpar(font=2,fontsize=25), rot=90)
        title = grid::textGrob("IPmix with uncertainty 5-95% CI", gp=grid::gpar(font=2,fontsize=25))
        gridExtra::marrangeGrob(plots, nrow=1, ncol=2, top=title, left=left_axis)
    }
}
```
