#!/usr/bin/perl

use FindBin qw($Bin);
use lib "$Bin/../lib"; #local
use lib '/opt/local64/PsN/PsN_4_5_7'; #cluster

use strict;
use Getopt::Long;
use Cwd;
use PsN;
use model;
use OSspecific;
use File::Copy 'cp';
use File::Glob;

#seed 76543 works
#my $lassooptions = ' -pred_ofv_start=100000000000 -min_retries=3 -relations=CL:WGT-2,APGR-2,,V:WGT-2,APGR-2 -stop_t=2';
#my $lassooptions = ' -min_retries=2 -no-normalize -pred_ofv_start=100000000000 -relations=CL:COV1-2,COV2-2,COV3-2,COV4-2,COV5-2,COV6-2,COV7-2,COV8-2,COV9-2,COV10-2';
my $lassooptions = ' -run_final_model -retries=5 -picky -stop_t=4 -log_scale -relations=CL:COV1-2,COV2-2,COV3-2,COV4-2,COV5-2,COV6-2,COV7-2,COV8-2,COV9-2,COV10-2 ';

sub absolute_pred_err{
	my $tablename = shift;
	my $ae=undef;
	if (-e $tablename){
		my @values=();
		open(RES,'<'.$tablename);
		foreach my $observation (<RES>) {
			next if ($observation =~ /^\s*TABLE/);
			next if ($observation =~ /^\s*ID/); #ID EVID DV PRED
			chomp $observation;
			$observation =~ s/^\s*//; #necessary, otherwise extra field
			my @items = split(/\s+/,$observation);
			next unless ($items[1] == 0); #EVID!=0
			next if ($items[2] == 0); #DV==0
			push(@values,abs($items[2]-$items[3])/abs($items[2]));
		}
		close(RES);
		if (scalar(@values)> 0){
			$ae=0;
			foreach my $val (sort { $a <=> $b } @values ) {
				$ae += $val;
			}
			$ae = 100*($ae/scalar(@values));
		}
	}
	return $ae;
}

#for testing agains lowriter
#print "res ".absolute_pred_err('test.tab')."\n";
#exit;

sub run_step{
    my $stepcounter = shift;
    my $command=shift;
    my $logfile = shift;
    my $maindir = shift;

    my $donefile = $maindir.'/step_'.$stepcounter.'.done';

    if (not -e $donefile){
		print "\nStep $stepcounter: Running $command\n ...";
		system("echo Step $stepcounter: Running $command ".' >>'.$logfile.' 2>&1');
		system($command.' >>'.$logfile.' 2>&1');
		system("echo Done ".' >'.$donefile);
    }else{
		my $message = "Skipping $command, done file step $stepcounter exists";
		print "$message\n";
		system("echo $message ".' >>'.$logfile.' 2>&1');
    }
}

my $cmd_line = $0 . " " . join( " ", @ARGV );

## Configure the command line parsing
Getopt::Long::config("auto_abbrev");

my %options;
## Declare the options

my %required_options = ('samples:i'=> '',
			'true_model:s'=> '',
			'seed:s'=> '',
			'external_dataset:s'=> '',
			'base_model:s' => '');
my %optional_options =('run_id:i' => '',
					   'extra_options:s'=> '');

my $res = GetOptions( \%options,
		      keys(%required_options),
		      keys(%optional_options) );
exit unless $res;

if( scalar(@ARGV) > 0 ){
  die "No arguments allowed apart from options";
}

foreach my $opt (keys %required_options){
    $opt =~ s/:.*//;
    unless ( defined $options{$opt} ){
		die "option $opt must be given\n" ;
    }
}

my $externaldata;
if (-e $options{'external_dataset'}){
	my ( $dir, $file ) = OSspecific::absolute_path(cwd(), $options{'external_dataset'});
	$externaldata = $dir . $file;
}else{
	die ('external data set '.$options{'external_dataset'}.' does not exist');
}

my $basedir=getcwd();

my $dirname;
if(defined $options{'run_id'}){
    $dirname='lasso_workflow_'.$options{'run_id'};
}else{
    #find new id
    for (my $id=1; $id<1000000; $id++){
		$dirname='lasso_workflow_'.$id;
		unless (-d $dirname){
			$options{'run_id'} = $id;
			last;
		}
    }
}
if(defined $options{'extra_options'}){
	$lassooptions .= ' '.$options{'extra_options'}; 
}

mkdir($dirname) unless (-d $dirname);
my $maindir = $basedir.'/'.$dirname;

my $logfile = $maindir.'/logfile.txt';
print "For detailed run progress check $logfile\n";


my $ssedir = $dirname.'/sserun';
my $ssecommand='sse '.$options{'true_model'}.' -samples='.$options{'samples'}.' -seed='.$options{'seed'}.
    ' -alt='.$options{'base_model'}.' -directory='.$ssedir;

my $stepcounter=1;
run_step($stepcounter++,$ssecommand,$logfile,$maindir);

my $lassomodeldir=$dirname.'/lasso_runs';

mkdir($lassomodeldir);
mkdir($dirname.'/evaluation_models');
#evaluation model for true model external data before cd
my $model = model -> new (filename  => $options{'true_model'},
						  ignore_missing_output_files => 1);
$model->set_maxeval_zero(need_ofv=> 1);
$model -> remove_records( type => 'covariance');
$model->datafiles(new_names =>[$externaldata],problem_numbers => [1]);
$model->relative_data_path(0);
$model->filename('evaluation_true.mod');
#For mae
$model -> add_records(type => 'table',
					  record_strings => ['ID EVID DV PRED NOAPPEND NOPRINT ONEHEADER FILE=dvpred_true.tab'],
					  problem_numbers => [1]);
$model->directory($maindir.'/evaluation_models/');
$model->_write(overwrite => 1);

chdir($ssedir.'/m1');
my @lassomodels=();
for (my $i=1; $i<= $options{'samples'}; $i++){
    my $ssemod = 'mc-alt_1-'.$i.'.';
    if (-e $ssemod.'lst'){
		my $out = 'sample'.$i.'.mod';
		my $command = 'update_inits '.$ssemod.'mod -out=../../lasso_runs/'.$out;
		run_step($stepcounter++,$command,$logfile,$maindir);
		push(@lassomodels,$out);
    }
    $ssemod = 'mc-orig-'.$i.'.';
    if (-e $ssemod.'lst'){
		$model = model -> new (filename  => $ssemod.'mod',
							   ignore_missing_output_files => 0);
		$model->update_inits(from_output => $model->outputs->[0]);
		$model -> remove_records( type => 'covariance');
		$model->set_maxeval_zero(need_ofv=> 1);
		$model->datafiles(new_names =>[$externaldata],problem_numbers => [1]);
		$model->relative_data_path(0);
		$model->filename('evaluation_type_sim_sample_'.$i.'.mod');
		$model -> add_records(type => 'table',
							  record_strings => ['ID EVID DV PRED NOAPPEND NOPRINT ONEHEADER FILE=dvpred_type_sim_sample_'.$i.'.tab'],
							  problem_numbers => [1]);
		
		$model->directory($maindir.'/evaluation_models/');
		$model->_write(overwrite => 1);
		
    }
}
unless (scalar(@lassomodels) == $options{'samples'}){

    print "something wrong with sse\n";
}
chdir('../../lasso_runs');

my @coeff_files=();
for (my $i=1; $i<= $options{'samples'}; $i++){
    my $mod = 'sample'.$i.'.mod'; #used inside lasso for naming evaluation model
    if (-e $mod){
		my $dir= 'lasso_1_'.$i;
		my $lassocommand='lasso '.$mod.' -adjusted -adaptive -seed='.($options{'seed'}+$i*111).' -directory='.$dir.
			' '.$lassooptions.' -external_data='.$externaldata;
		run_step($stepcounter++,$lassocommand,$logfile,$maindir);
		push(@coeff_files,$dir.'/lasso_coefficients.csv') if (-e $dir.'/lasso_coefficients.csv');

		my $filename = 'evaluation_type_aal_sample_'.$i.'.mod';
		my $optname = 'optimal_type_aal_sample_'.$i.'.lst';
		my $outname = 'evaluation_updated_type_aal_sample_'.$i.'.mod';
 		if (-e $dir.'/m1/'.$filename){
			if (-e $dir.'/m1/'.$optname){
				chdir($dir.'/m1');
				my $command = 'update_inits '.$filename.' '.$optname.' -out='.$outname;
				system($command.' >>'.$logfile.' 2>&1');
				$model = model -> new (filename  => $outname,
									   ignore_missing_output_files => 1);
				$model->relative_data_path(0);
				$model -> set_records(type => 'table',
									  record_strings => ['ID EVID DV PRED NOAPPEND NOPRINT ONEHEADER FILE=dvpred_updated_type_aal_sample_'.$i.'.tab'],
									  problem_numbers => [1]);
		
				$model->directory($maindir.'/evaluation_models/');
				$model->_write(overwrite => 1);
				chdir('../..');
			}
			cp($dir.'/m1/'.$filename,'../evaluation_models/.');
		}

		my $dir= 'lasso_2_'.$i;
		my $lassocommand='lasso '.$mod.' -adaptive -seed='.($options{'seed'}+$i*111).' -directory='.$dir.
			' '.$lassooptions.' -external_data='.$externaldata;
		run_step($stepcounter++,$lassocommand,$logfile,$maindir);
		push(@coeff_files,$dir.'/lasso_coefficients.csv') if (-e $dir.'/lasso_coefficients.csv');
		$filename = 'evaluation_type_l_sample_'.$i.'.mod';
 		$optname = 'optimal_type_l_sample_'.$i.'.lst';
		$outname = 'evaluation_updated_type_l_sample_'.$i.'.mod';
 		if (-e $dir.'/m1/'.$filename){
			if (-e $dir.'/m1/'.$optname){
				chdir($dir.'/m1');
				my $command = 'update_inits '.$filename.' '.$optname.' -out='.$outname;
				system($command.' >>'.$logfile.' 2>&1');
				$model = model -> new (filename  => $outname,
									   ignore_missing_output_files => 1);
				$model->relative_data_path(0);
				$model -> set_records(type => 'table',
									  record_strings => ['ID EVID DV PRED NOAPPEND NOPRINT ONEHEADER FILE=dvpred_updated_type_l_sample_'.$i.'.tab'],
									  problem_numbers => [1]);
		
				$model->directory($maindir.'/evaluation_models/');
				$model->_write(overwrite => 1);
				chdir('../..');
			}
			cp($dir.'/m1/'.$filename,'../evaluation_models/.');
		}
		$filename = 'evaluation_type_al_sample_'.$i.'.mod';
 		$optname = 'optimal_type_al_sample_'.$i.'.lst';
		$outname = 'evaluation_updated_type_al_sample_'.$i.'.mod';
 		if (-e $dir.'/m1/'.$filename){
			if (-e $dir.'/m1/'.$optname){
				chdir($dir.'/m1');
				my $command = 'update_inits '.$filename.' '.$optname.' -out='.$outname;
				system($command.' >>'.$logfile.' 2>&1');
				$model = model -> new (filename  => $outname,
									   ignore_missing_output_files => 1);
				$model->relative_data_path(0);
				$model -> set_records(type => 'table',
									  record_strings => ['ID EVID DV PRED NOAPPEND NOPRINT ONEHEADER FILE=dvpred_updated_type_al_sample_'.$i.'.tab'],
									  problem_numbers => [1]);
		
				$model->directory($maindir.'/evaluation_models/');
				$model->_write(overwrite => 1);
				chdir('../..');
			}
			cp($dir.'/m1/'.$filename,'../evaluation_models/.');
		}
    }else{
		print "input model $mod for lasso missing for sample $i\n";
    }
}

my @result=();

foreach my $file (@coeff_files){
    $file =~ /^lasso_(\d+)_(\d+)/ ;
    my $ver = $1;
    my $num = $2;
    if (-e $file){
		open (RES,$file);
		my @lines = <RES>;
		close(RES);
		if (scalar(@result)==0){
			#first: add a header
			chomp $lines[0];
			push(@result,'sample,type,'.$lines[0]);
		}
		chomp $lines[1];

		if ($ver == 1){
			#adjusted adaptive, only one row
			push(@result,$num.',aal,'.$lines[1]);
		}else{
			#adaptive, two rows
			push(@result,$num.',l,'.$lines[1]);
			if (scalar(@lines)>2){
				chomp $lines[2] ;
				push(@result,$num.',al,'.$lines[2]);
			}
		}
    }
}

chdir('..');

open(RES,'>final_lasso_coefficients.csv');
foreach my $line (@result){
    print RES $line."\n";
}
close(RES);

#glob for filenames
#execute using join for command
#parse rawres, use model col (index 0) and ofv (index 18)
#print new csv file with results
chdir('evaluation_models');

my @files = <*.mod>;

my $command='execute -no-disp '.join(' ',@files).' -dir=rundir ';
run_step($stepcounter++,$command,$logfile,$maindir);

my $filename = $files[0];
$filename =~ s/mod$/csv/;
open(RES,'<rundir/raw_results_'.$filename);
my @lines = <RES>;
close(RES);
my @ofvs=('model,type,sample,ofv,ae');

for (my $i=1; $i<scalar(@lines); $i++){
	my @fields = split(',',$lines[$i]);
	my $modelnum = $fields[0];
	my $sample=undef;
	my $tablename;
	if ($files[$modelnum-1] =~ /_sample_(\d+)\./){
		$sample = $1;
	}
	my $type = undef;
	if ($files[$modelnum-1] =~ /_type_([a-z0-9]+)_/){
		$type = $1;
		if ($files[$modelnum-1] =~ /_updated_/){
			$tablename = 'dvpred_updated_type_'.$type.'_sample_'.$sample.'.tab';
		}else{
			$tablename = 'dvpred_type_'.$type.'_sample_'.$sample.'.tab';
		}
	}else{
		$tablename = 'dvpred_true.tab';
	}
	my $ae =absolute_pred_err($tablename);
	my $ofv = $fields[19] if (scalar(@fields)>19);
	push(@ofvs,$files[$modelnum-1].','.$type.','.$sample.','.$ofv.','.$ae);
}
chdir('..');
open(RES,'>evaluation_ofv.csv');
foreach my $line (@ofvs){
    print RES $line."\n";
}
close(RES);

print "\nDone\n";
