name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install build dependencies
        run: sudo apt install latexmk texlive-extra-utils texlive-latex-extra texlive-generic-extra biber texlive-bibtex-extra texlive-science texlive-font-utils and texlive-pictures tox 
      - run: make
      - run: make release
      - uses: actions/upload-artifact@v2
        with:
          name: targz
          path: PsN-*.tar.gz

  test-ubuntu:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: targz 
      - run: tar -zxvf PsN-*.tar.gz
      - run: sudo cpan Math::Random
      - run: sudo cpan YAML::XS
      - run: sudo apt update
      - run: sudo apt install -y libtest-exception-perl libmoose-perl libmoosex-params-validate-perl libarchive-zip-perl libfile-copy-recursive-perl r-base pandoc libpq-dev libcairo2-dev libssl-dev libcurl4-openssl-dev libmariadb-dev libgmp-dev libmpfr-dev libxml2-dev libudunits2-dev libblas-dev liblapack-dev libmagick++-dev
      - run: cd PsN-Source; sudo perl setup.pl -auto

  test-macos:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: targz 
      - run: tar -zxvf PsN-*.tar.gz
      - run: sudo cpan Math::Random
      - run: sudo cpan Moose
      - run: sudo cpan MooseX::Params::Validate
      - run: sudo cpan Archive::Zip
      - run: sudo cpan File::Copy::Recursive
      - run: sudo cpan YAML::XS
      - run: sudo cpan Test::Exception

  build-windows:
      needs: build
      runs-on: windows-latest
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: targz 
