name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source repo 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install build dependencies
        run: sudo apt install latexmk texlive-extra-utils texlive-latex-extra texlive-generic-extra biber texlive-bibtex-extra texlive-science texlive-font-utils and texlive-pictures tox 
      - name: make
        run: make
      - name: make release 
        run: make release
      - name: Upload installation artifact
        uses: actions/upload-artifact@v2
        with:
          name: targz
          path: PsN-*.tar.gz
      - name: Upload documentation artifact 
        uses: actions/upload-artifact@v2
        with:
            name: docs 
            path: doc/*.pdf

  test-ubuntu:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: targz 
      - run: tar -zxvf PsN-*.tar.gz
      - run: sudo cpan -T Math::Random
      - run: sudo cpan -T YAML::XS
      - run: sudo apt update
      - name: Install Perl and R dependencies
        run: sudo apt install -y libtest-exception-perl libmoose-perl libmoosex-params-validate-perl libarchive-zip-perl libfile-copy-recursive-perl r-base pandoc libpq-dev libcairo2-dev libssl-dev libcurl4-openssl-dev libmariadb-dev libgmp-dev libmpfr-dev libxml2-dev libudunits2-dev libblas-dev liblapack-dev libmagick++-dev
      - name: Install PsN 
        run: cd PsN-Source; sudo perl setup.pl -auto

  test-macos:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download installation tarball
        uses: actions/download-artifact@v2
        with:
          name: targz 
      - name: Unpack installation tarball 
        run: tar -zxvf PsN-*.tar.gz
      - name: Install system dependencies
        run: brew install r pandoc cairo mariadb-connector-c openssl@1.1
      - name: Install gfortran
        run: brew reinstall gcc
      - name: Install Math::Random
        run: sudo cpan -T Math::Random
      - name: Install Moose
        run: sudo cpan -T Moose
      - name: Install MooseX::Params::Validate 
        run: sudo cpan -T MooseX::Params::Validate
      - name: Install Archive::Zip 
        run: sudo cpan -T Archive::Zip
      - name: Install File::Copy::Recursie 
        run: sudo cpan -T File::Copy::Recursive
      - name: Install YAML::XS 
        run: sudo cpan -T YAML::XS
      - name: Install Test::Exception 
        run: sudo cpan -T Test::Exception
#      - name: Set fortran compiler
#        run: |
#          echo '#!/bin/bash' >/usr/local/bin/gfortran
#          echo 'gfortran-9 "$@"' >>/usr/local/bin/gfortran
#          chmod u+x /usr/local/bin/gfortran
      - name: Install PsN
        run: cd PsN-Source; perl setup.pl -auto


  build-windows:
      needs: build
      runs-on: windows-latest
      steps:
        - name: Download installation tarball
          uses: actions/download-artifact@v2
          with:
            name: targz 
        - name: Download Strawberry Perl
          uses: suisei-cn/actions-download-file@v1
          with:
            url: http://strawberryperl.com/download/5.22.3.1/strawberry-perl-5.22.3.1-64bit-portable.zip
            target: downloads/
        - name: Download R
          uses: suisei-cn/actions-download-file@v1
          with:
            url: https://cran.r-project.org/bin/windows/base/R-4.0.3-win.exe
            target: downloads/
        - name: Download Python
          uses: suisei-cn/actions-download-file@v1
          with:
            url: https://github.com/winpython/winpython/releases/download/2.3.20200530/Winpython64-3.7.7.1dot.exe
            target: downloads/
        - name: Download Pandoc
          uses: suisei-cn/actions-download-file@v1
          with:
            url: https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-windows-i386.zip
            target: downloads/
        - name: Show downloads
          run: dir downloads
          shell: cmd
        - name: Create installation directory
          run: |
             md -Name installer
             md -Name installer\strawberry
        - name: Extract Strawberry Perl
          run: tar -xf downloads/strawberry-perl-5.22.3.1-64bit-portable.zip -C installer\strawberry
        - name: Install perl modules
          run: |
            cd installer\strawberry
            portableshell.bat
            cpanm Params::Validate --notest 
            cpanm MooseX::Params::Validate --notest 
            cpanm Math::Random --notest 
          shell: cmd
        - name: Install PsN
          run: |
              cd installer\strawberry
              portableshell.bat
              cd ..\..
              cd PsN-Source
              perl setup.pl relative --auto
          shell: cmd
        - name: Extract pandoc
          run: tar -xf downloads/pandoc-2.5-windows-i386.zip -C installer
        - name: Install R
          run: downloads\R-4.0.3-win.exe /VERYSILENT /DIR="installer\R"
          shell: cmd
        - name: Install renv
          run: |
            md installer\Rlib
            installer\R\bin\i386\Rscript.exe -e "install.packages('renv', lib='installer\Rlib', repos='http://cran.us.r-project.org')"
          shell: cmd
        - name: Show installer directory
          run: dir installer\R
          shell: cmd
