name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install build dependencies
        run: sudo apt install latexmk texlive-extra-utils texlive-latex-extra texlive-generic-extra biber texlive-bibtex-extra texlive-science texlive-font-utils and texlive-pictures tox 
      - run: make
      - run: make release
      - name: Upload installation artifact
        uses: actions/upload-artifact@v2
        with:
          name: targz
          path: PsN-*.tar.gz
      - name: Upload documentation artifact 
        uses: actions/upload-artifact@v2
        with:
            name: docs 
            path: doc/*.pdf

  test-ubuntu:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: targz 
      - run: tar -zxvf PsN-*.tar.gz
      - run: sudo cpan Math::Random
      - run: sudo cpan YAML::XS
      - run: sudo apt update
      - name: Install Perl and R dependencies
        run: sudo apt install -y libtest-exception-perl libmoose-perl libmoosex-params-validate-perl libarchive-zip-perl libfile-copy-recursive-perl r-base pandoc libpq-dev libcairo2-dev libssl-dev libcurl4-openssl-dev libmariadb-dev libgmp-dev libmpfr-dev libxml2-dev libudunits2-dev libblas-dev liblapack-dev libmagick++-dev
      - name: Install PsN 
        run: cd PsN-Source; sudo perl setup.pl -auto

  test-macos:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: targz 
      - run: tar -zxvf PsN-*.tar.gz
      - run: brew install gcc r pandoc cairo mariadb-connector-c openssl@1.1
      - run: sudo cpan Math::Random
      - run: sudo cpan Moose
      - run: sudo cpan MooseX::Params::Validate
      - run: sudo cpan Archive::Zip
      - run: sudo cpan File::Copy::Recursive
      - run: sudo cpan YAML::XS
      - run: sudo cpan Test::Exception
      - name: Install PsN
        run: cd PsN-Source; perl setup.pl -auto


  build-windows:
      needs: build
      runs-on: windows-latest
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: targz 
        - name: Download Strawberry Perl
          uses: suisei-cn/actions-download-file@v1
          with:
            url: http://strawberryperl.com/download/5.22.3.1/strawberry-perl-5.22.3.1-64bit-portable.zip
            target: downloads/
        - name: Download R
          uses: suisei-cn/actions-download-file@v1
          with:
            url: https://cran.r-project.org/bin/windows/base/R-4.0.0-win.exe
            target: downloads/
        - name: Download Python
          uses: suisei-cn/actions-download-file@v1
          with:
            url: https://github.com/winpython/winpython/releases/download/2.3.20200530/Winpython64-3.7.7.1dot.exe
            target: downloads/
        - name: Download Pandoc
          uses: suisei-cn/actions-download-file@v1
          with:
            url: https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-windows-i386.zip
            target: downloads/
        - name: Create installation directory
          run: md -Name installer
        - name: Extract Strawberry Perl
          run: tar -xf downloads/strawberry-perl-5.22.3.1-64bit-portable.zip
        - name: Show downloads
          run: dir downloads
          shell: cmd
        - name: Install R
          run: downloads\R-4.0.0-win.exe /VERYSILENT /DIR="installer\R"
          shell: cmd
