name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download assets
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
                targz/*
                docs/*
                wininstaller/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
