name: linux-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: sudo cpan Math::Random
      - run: sudo cpan Moose
      - run: sudo cpan MooseX::Params::Validate
      - run: sudo cpan Archive::Zip
      - run: sudo cpan File::Copy::Recursive
      - run: sudo cpan YAML::XS
      - run: prove test/unit -r -j8
      - run: sudo apt install latexmk texlive-extra-utils texlive-latex-extra texlive-generic-extra biber texlive-bibtex-extra texlive-science texlive-font-utils and texlive-pictures tox 
      - run: make
      - run: make release
